version: '3.8'

services:
  backend:
    container_name: django-order-service-backend
    build: .
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - TZ=Asia/Seoul
  
  db:
    container_name: django-order-service-db
    image: mysql:8.0.11
    restart: always
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306